version: '3.8'

services:
  app-simplemsg-painel:
    build: .
    container_name: app-simplemsg-painel
    restart: unless-stopped
    networks:
      - pwbot_net
    environment:
      - VIRTUAL_HOST=painel.simplemsg.net.br
      - LETSENCRYPT_HOST=painel.simplemsg.net.br
      - LETSENCRYPT_EMAIL=suporte@produtoweb.com.br

networks:
  pwbot_net:
    external: true
